### ISSUE TITLE
do you consider add security and send messages to special user

### ISSUE THREAD

**Issue by keryhu** [tisztamo/adslist-spring#2]
Hi, this is a good example ..

recently ,i try to use websocket and angular2 , spring can send messages publish/subscribe,

but met problems with sending messages to special user.

Don't know if you will consider adding this feature？ or give some suggestion

**Comment by tisztamo** [comment]
Hi, this software is an example for security trainings, it contains numerous security vulnerabilities. Please do not use it as an example as you may also introduce security issues into your system! I will update the readme to better highlight this nature of the app.
